--- 
javascripts: 
- base:
  - jquery
  - jquery-ui
  - jquery.livequery
  - application
  - pretty_flash
- invoices:
  - invoices
  - auto_resize_textareas
  - edit_in_place
- new_invoice:
  - new_invoice_form
stylesheets: 
- base: 
  - default
  - pretty_flash
- invoices:
  - invoices
- invoice:
  - invoice
- calendar:
  - calendar
