development: &login
  adapter: mysql
  database: eboshi
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

staging:
  <<: *login

test: &test
  <<: *login
  database: eboshi_test

cucumber:
  <<: *test
